name: Deploy to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy static website to Azure Storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.26.0
          inlineScript: |
            az storage blob upload-batch --account-name cloudresumestoragev2 --auth-mode key -d '$web' -s .
            

   # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
