name: Update Azure Static Website

on:
  push:
    branches:
      - main

jobs:
  update_static_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}v

      - name: Install Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          version: latest

      - name: Update index.html file
        run: az storage blob upload-batch --account-name cloudresumestoragev2 --destination $web --source . --pattern index.html --overwrite

      - name: Invalidate CDN cache
        if: ${{ always() }}
        uses: Azure/invalidate-cdn@v1
        with:
          resource-group-name: <your-resource-group-name>
          endpoint-name: <your-endpoint-name>
          paths: /index.html
          
          # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
