name: Blob storage website CI

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Update index.html file
      run: az storage blob upload-batch --account-name <your-storage-account-name> --destination <your-container-name> --source . --pattern index.html --overwrite

    name: Invalidate CDN cache
    if: ${{ always() }}
    uses: Azure/invalidate-cdn@v1
    with:
          resource-group-name: <your-resource-group-name>
          endpoint-name: <your-endpoint-name>
          paths: /index.html
          
# Azure logout
  name: logout
  run: |
            az logout
      if: always()
