name: Deploy to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy static website to Azure Storage
        uses: azure/cli-action
        with:
          azcliversion: 2.26.0
          inlineScript: |
            az storage blob upload-batch --destination $web --source . --account-name cloudresumestoragev2
