name: Update Azure Static Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          version: latest

      - name: Update index.html file
        run: az storage blob upload-batch --account-name cloudresumestoragev2 --destination $web --source . --pattern index.html --overwrite

      - name: Invalidate CDN cache
        if: ${{ always() }}
        uses: Azure/invalidate-cdn@v1
        with:
          resource-group-name: CloudResume-Challenge-RG
          endpoint-name: alex-cloud-resume (staticwebsite-cdn/alex-cloud-resume)
          paths: /index.html
        env:
          AZURE_CDN_SUBSCRIPTION_ID: ${{ secrets.AZURE_CDN_SUBSCRIPTION_ID }}
          AZURE_CDN_TENANT_ID: ${{ secrets.AZURE_CDN_TENANT_ID }}
          AZURE_CDN_CLIENT_ID: ${{ secrets.AZURE_CDN_CLIENT_ID }}
          AZURE_CDN_CLIENT_SECRET: ${{ secrets.AZURE_CDN_CLIENT_SECRET }}
